#.travis.yml

language: node_js
node_js:
  - "8.1.0"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - npm run build:universal

after_success:
  - firebase use eoriolfront
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change