#.travis.yml

language: node_js

node_js:
  - "8.11.2"

branches:
  only:
    - master
    - /^release-.*$/

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - echo $TRAVIS_BRANCH
  - npm run build:universal

after_success:
  - if [ $TRAVIS_BRANCH == "master" ]; then
      firebase use eoriolfront;
    else
      firebase use eoriolfront-staging;
    fi
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change